---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: vaultwarden
  managedSecret:
    name: vaultwarden-managed-secret
    namespace: vaultwarden
