# MANAGED BY DOPPLER - manual values replaced on first sync
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/part-of: homelab
stringData:
  ACCESS_KEY_ID: MANAGED_BY_DOPPLER
  SECRET_ACCESS_KEY: MANAGED_BY_DOPPLER
