apiVersion: v1
kind: Namespace
metadata:
  name: memos
  labels:
    app.kubernetes.io/name: memos
    app.kubernetes.io/part-of: homelab
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
