---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/part-of: homelab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Keylessboi/k8s-gitops.git
    targetRevision: main
    path: apps/flaresolverr
  destination:
    server: https://kubernetes.default.svc
    namespace: flaresolverr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
