---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: authentik
  managedSecret:
    name: authentik-managed-secret
    namespace: authentik
