---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: lidarr-secrets
  namespace: lidarr
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: lidarr
  managedSecret:
    name: lidarr-managed-secret
    namespace: lidarr
