apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-data
  namespace: obsidian
  labels:
    app.kubernetes.io/name: obsidian
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
