---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: nextcloud
  managedSecret:
    name: nextcloud-managed-secret
    namespace: nextcloud
