# MANAGED BY DOPPLER - manual values replaced on first sync
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-minio
  namespace: nextcloud
type: Opaque
stringData:
  ACCESS_KEY_ID: MANAGED_BY_DOPPLER
  SECRET_ACCESS_KEY: MANAGED_BY_DOPPLER
