---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: navidrome-secrets
  namespace: navidrome
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: navidrome
  managedSecret:
    name: navidrome-managed-secret
    namespace: navidrome
