apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
