# MANAGED BY DOPPLER - manual values replaced on first sync
apiVersion: v1
kind: Secret
metadata:
  name: navidrome-minio
  namespace: navidrome
type: Opaque
stringData:
  ACCESS_KEY_ID: MANAGED_BY_DOPPLER
  ACCESS_SECRET_KEY: MANAGED_BY_DOPPLER
