---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: immich
  managedSecret:
    name: immich-managed-secret
    namespace: immich
