apiVersion: v1
kind: Namespace
metadata:
  name: immich
  labels:
    homelab/data-class: c3
    homelab/criticality: tier-2
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: homelab
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
