apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: prowlarr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - prowlarr.sandstorm.chat
    secretName: prowlarr-tls
  rules:
  - host: prowlarr.sandstorm.chat
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr-main
            port:
              number: 9696
