---
apiVersion: v1
kind: Namespace
metadata:
  name: music
  labels:
    app.kubernetes.io/name: music
    app.kubernetes.io/part-of: homelab
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
