apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix
  namespace: kiwix
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-rate-limit@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - kiwix.sandstorm.chat
    secretName: kiwix-tls
  rules:
  - host: kiwix.sandstorm.chat
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kiwix
            port:
              number: 8080
