apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-acquis
  namespace: pangolin
data:
  acquis.yaml: |
    source: file
    filenames:
      - /var/log/traefik/*.log
    labels:
      type: traefik
