---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: pangolin-secrets
  namespace: pangolin
spec:
  project: "proxmox"
  config: "prd"
  tokenSecret:
    name: doppler-token
    namespace: pangolin
  managedSecret:
    name: pangolin-managed-secret
    namespace: pangolin
