apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pangolin-data
  namespace: pangolin
  labels:
    app.kubernetes.io/name: pangolin
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs
  resources:
    requests:
      storage: 2Gi
