---
apiVersion: v1
kind: Namespace
metadata:
  name: downloads
  labels:
    app.kubernetes.io/name: downloads
    app.kubernetes.io/part-of: homelab
    # gluetun needs NET_ADMIN and /dev/net/tun to bring up WireGuard.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
