---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: accounts
spec:
  selector:
    app.kubernetes.io/name: accounts
  ports:
    - name: http
      port: 80
      targetPort: 8080
