apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    homelab/data-class: c3
    homelab/criticality: tier-2
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: homelab
    homelab/tier: platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
